# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tools here

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py
   fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf
   - epub

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/requirements.txt
   - method: pip
     path: .
     extra_requirements:
       - docs

# Optional but recommended, specify the Python version to use
# https://docs.readthedocs.io/en/stable/config-file/v2.html#python
